### ISSUE TITLE
Host-based anomaly detection event (rootcheck)

### ISSUE THREAD

**Issue by knzudgt** [ossec/ossec-hids#1855] opened 2020-03-18 14:04 UTC
I use [dokku](https://github.com/dokku/dokku) in a Ubuntu 18.04 LTS machine.
I received the following alerts concerning files hidden in a long list of directories:

    Rule: 510 fired (level 7) -> "Host-based anomaly detection event (rootcheck)."
    Portion of the log(s):

    Files hidden inside directory '/var/lib/docker/overlay2/c3ee7713915112e9bd1df6d423cc6e2dd35a6d1c9871daae8c53054c05408516/merged/usr/share/man'. Link count does not match number of files (26,1).

Then again:

    Files hidden inside directory '/var/lib/docker/overlay2/c3ee7713915112e9bd1df6d423cc6e2dd35a6d1c9871daae8c53054c05408516/merged/usr/share/dpkg'. Link count does not match number of files (2,1).

And so on for a list of 104 directories, like `/var/lib/docker/overlay2/c3ee7713915112e9bd1df6d423cc6e2dd35a6d1c9871daae8c53054c05408516/merged/usr/sbin` or `/var/lib/docker/overlay2/c3ee7713915112e9bd1df6d423cc6e2dd35a6d1c9871daae8c53054c05408516/merged/usr/bin` etc etc

How am I expected to interpret these alerts? What am I expected to do?

**Comment by ddpbsd** [comment] 2020-03-27 17:27
`rootcheck` doesn't understand about overlays yet.

**Comment by knzudgt** [comment] 2020-03-28 15:47
@ddpbsd what does it mean that rootcheck doesn't understand about overlays? Sorry, but I do not know what an overlay is. Are you saying that probably these are false positives?

**Comment by ddpbsd** [comment] 2020-03-30 22:21
@knzudgt I don't understand overlays very well myself. Anyone with more/better knowledge than me should feel free to comment, correct, and educate us all. 
From the little I do understand I've gathered that they change the way applications on the host system see those parts of the filesystem. So something that exists inside of a container's filesystem might not be visible outside of that container in the same way. So OSSEC, using older techniques sees a discrepancy between how many files should be there and how many files are actually there (outside of the container) and this triggers the alert.

**Comment by mlissner** [comment] 2021-02-19 01:02
Wazuh has a one-line fix for this, here: https://github.com/wazuh/wazuh/commit/460a2d2dd5706789774f425e88335b0ca74ffb57

Also, this is a dup of: https://github.com/ossec/ossec-hids/issues/1528.

Until we can get that fix in place, is there a way to snuff out these false positives?

**Comment by atomicturtle** [comment] 2021-02-21 18:52
Thanks for the followup and the duplicate identification. Im going to merge this into 1528 before the PR

Duplicate of: #1528

**Closed by atomicturtle** 2021-02-21 18:52 UTC
