### ISSUE TITLE
Error installing (makefile)

### ISSUE THREAD

**Issue by abbeazale** [ossec/ossec-hids#1935] opened 2020-11-24 04:38 UTC
on kali linux after using ./install.sh it returns the following error

```
5- Installing the system
 - Running the Makefile
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" 
-DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DMYSQL_DATABASE_ENABLED -DLIBOPENSSL_ENABLED -Wall -Wextra -I./ -I./headers/  
client-agent/agentd.o client-agent/config.o client-agent/event-forward.o client-agent/intcheck_op.o client-agent/main.o client-agent/notify.o client-agent/receiver.o 
client-agent/receiver-win.o client-agent/sendmsg.o client-agent/start_agent.o os_dns/os_dns.o os_crypto.a config.a shared.a os_net.a os_regex.a os_xml.a os_zlib.a  
-lm -lpthread -lpcre2-8 -L/usr/lib/x86_64-linux-gnu/ -lmariadb -lssl -lcrypto -lz  -levent ./external/compat/imsg.c ./external/compat/imsg-buffer.c -o ossec-agentd
/usr/bin/ld: client-agent/config.o:(.bss+0x0): multiple definition of `server_ibuf'; client-agent/agentd.o:(.bss+0x0): first defined here
/usr/bin/ld: client-agent/event-forward.o:(.bss+0x0): multiple definition of `server_ibuf'; client-agent/agentd.o:(.bss+0x0): first defined here
/usr/bin/ld: client-agent/intcheck_op.o:(.bss+0x0): multiple definition of `server_ibuf'; client-agent/agentd.o:(.bss+0x0): first defined here
/usr/bin/ld: client-agent/main.o:(.bss+0x0): multiple definition of `server_ibuf'; client-agent/agentd.o:(.bss+0x0): first defined here
/usr/bin/ld: client-agent/notify.o:(.bss+0x0): multiple definition of `server_ibuf'; client-agent/agentd.o:(.bss+0x0): first defined here
/usr/bin/ld: client-agent/receiver.o:(.bss+0x0): multiple definition of `server_ibuf'; client-agent/agentd.o:(.bss+0x0): first defined here
/usr/bin/ld: client-agent/sendmsg.o:(.bss+0x0): multiple definition of `server_ibuf'; client-agent/agentd.o:(.bss+0x0): first defined here
/usr/bin/ld: client-agent/start_agent.o:(.bss+0x0): multiple definition of `server_ibuf'; client-agent/agentd.o:(.bss+0x0): first defined here
/usr/bin/ld: os_net.a(os_net.o):(.bss+0x0): multiple definition of `agt'; client-agent/config.o:(.bss+0x10088): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:1020: ossec-agentd] Error 1

 Error 0x5.
 Building error. Unable to finish the installation.
```

I've made sure all my packages are up to date and I've been trouble shooting but no so far no luck.

**Comment by ddpbsd** [comment] 2020-11-25 19:03
Looks like issue #1871

**Comment by atomicturtle** [comment] 2021-02-21 19:24
Yeah, this is #1871, and its now merged. Confirmed fixed

**Closed by atomicturtle** 2021-02-21 19:24 UTC
