### ISSUE TITLE
OSSEC-HIDS 3.6 cant install or reinstall the service - on windows

### ISSUE THREAD

**Issue by eyaladmin** [ossec/ossec-hids#1851] opened 2020-03-03 23:02 UTC
HI

kindly check why "OssecSvc" service failed with installation file
It happened on a fresh installation or when upgrading from 3.3 or when uninstalling

Thanks

**Comment by tmeader** [comment] 2020-03-03 23:54
I saw the exact same thing when I attempted to upgrade. Had to uninstall completely and rollback to the 3.3 client on Windows. It may be best if the 3.6 Windows client is removed from the website until this can be resolved.

**Comment by RabidGerbal** [comment] 2020-03-04 00:26
See issue #1849

**Comment by atomicturtle** [comment] 2020-03-15 18:00
duplicate of #1849

**Closed by atomicturtle** 2020-03-15 18:00 UTC
