### ISSUE TITLE
Can not run the Windows agent on non-English Windows systems 

### ISSUE THREAD

**Issue by jbcheng** [ossec/ossec-hids#616] opened 2015-05-20 17:18 UTC
From: Laurenz
 
There is a conflict with the hard-coded administrator account name inside the windows agent. You can’t run the windows agent on windows systems that are not English. The bug persists for more than a year. 

See description: https://groups.google.com/forum/#!topic/ossec-list/MCBBnWAwa8U
 
See related info from Microsoft: https://support.microsoft.com/en-us/kb/157234

**Comment by awiddersheim** [comment] 2015-05-20 17:22
This is a duplicate of #303. Should be fixed in the 2.9 release which is still in beta. Still looking for people to test.

Also see: https://groups.google.com/d/topic/ossec-list/gdQdqlbCn98/discussion

**Closed by awiddersheim** 2015-05-20 17:22 UTC
