### ISSUE TITLE
Please remove apt-get instructions from the OSSEC website

### ISSUE THREAD

**Issue by ejratl** [ossec/ossec-hids#738] opened 2016-01-29 19:03 UTC
Please remove he following instructions on the OSSEC downloads page (http://ossec.github.io/downloads.html)

> Step 1. Install the apt-get repository key:
> # apt-key adv --fetch-keys http://ossec.wazuh.com/repos/apt/conf/ossec-key.gpg.key

These instructions open users up to an unacceptable level of risk. To understand why this is the case, please have a look at this Stack Exchange Q&A ( http://security.stackexchange.com/questions/86791/is-adding-apt-keys-using-wget-secure) which describes the issues.

**Comment by ddpbsd** [comment] 2016-01-29 19:05
Can you suggest better instructions I can replace them with?

**Comment by aremai** [comment] 2016-01-29 20:48
do you mean because it's not using https??
on RHEL-based systesm there's the option to also add the gpgcheck...not sure if debian-based systems have this option too?!

**Comment by ejratl** [comment] 2016-01-29 22:11
I would recommend that you get a free SSL certificate for ossec.github.io via Let's Encrypt https://letsencrypt.org/howitworks/ Then host the key on the ossec website rather than the developer's website. Include instructions to download the key and at least check the fingerprint (which you publish on your website) before importing it as a trusted installation key.

**Comment by jrossi** [comment] 2016-01-29 22:18
https://ossec.github.io has a cert and just a simple change to make this use tls.

**Comment by santiago-bassett** [comment] 2016-01-30 01:51
yes, I think that makes sense. I'll also install an SSL certificate in Wazuh repository, just in case.

**Comment by fschwebel** [comment] 2016-05-02 14:07
Honestly, that's critical and an example of what discredits OSSEC. It's a security product, one with potential root access to huge networks. Its distribution should be 100% secure with ubiquitous TLS, GPG signing and reproducible builds.
Currently the Download OSSEC page kind of says: give your machines root access to Wazuh and other OSSEC contributors, but also to your own network infrastructure providers and managers, your ISP, your government and a bunch of 3-letters agencies. It could just about Wazuh (and the agencies :)). Imho it's better to not provide binaries/DEBs rather than proposing an insecure installation.

**Comment by aremai** [comment] 2016-05-02 18:44
Please be a little more specific in what you mean with "reproducible builds" and "an insecure installation" ;)

**Comment by fschwebel** [comment] 2016-05-02 19:01
Hello @aremai 
For reproducible builds, see [this great website](https://reproducible-builds.org/). In a few words, building inside a well defined environment (such as a Vagrant VM) in a deterministic way allow the users to compare the available source with the provided binaries. I used the words "an insecure installation" because you may very well need OSSEC if by setting it up you have to trust any software package signed by some key that may or may not come from a defined party ;).
Still, I want to clarify I think OSSEC is an amazing piece of software! However, and even if you are privileged enough to not have to worry about it that much (let's say, in the USA or in Europe), please remember that some of your users do care, and have reasons to. Securing the delivery of your (again, great) software is **really** important.

**Comment by ddpbsd** [comment] 2016-05-03 12:01
@fschwebel And it is a process we are working on, unfortunately it isn't free (time and effort).

**Comment by tobowers** [comment] 2016-09-07 07:22
Hey guys, I want to be cautious in my tone here... I'm saying this with love! :).

I'd like to use the wazuh repo to install the agent, but it doesn't seem to offer SSL yet and so it's kind of unusable.

The atomiccorp repos only installation instructions are to pipe a script to `sh` which is also pretty unusable... Right now i'm parsing through that script to see if I can just setup the repo manually, but that seems like it might be a license problem given that the script has a "do you accept?"

I was also considering using a public github repo of my own to host an ssl version of the wazuh public key...

I'm happy to volunteer to help with SSL. My linux package distribution knowledge is not large, but anyway I can make this better/easier I am motivated.

**Comment by moses** [comment] 2016-11-26 21:14
Hi @santiago-bassett and @ddpbsd - Is there a plan yet for resolving this? Any way I can help? Thanks for all your work on OSSEC.

**Comment by ddpbsd** [comment] 2016-11-27 00:04
The wuzah instructions have been removed. The page is for ossec, not ossec. What else are you offering to do @moses?

**Comment by jsmpereira** [comment] 2016-12-14 11:11
Seems that the wazuh instructions are still available in the docs - http://ossec.github.io/docs/manual/installation/installation-package.html.

**Comment by jlruizmlg** [comment] 2016-12-14 15:06
Hi guys, Wazuh repository has now https, and in a few days the repository will be reallocate in CloudFront as well.

**Comment by metaclass-nl** [comment] 2017-04-22 12:39
This uses SSL:

wget -qO - https://ossec.wazuh.com/repos/apt/conf/ossec-key.gpg.key | sudo apt-key add -

**Closed** 2018-10-23 16:42 UTC
